// src/components/MarkdownRenderer.tsx
import Markdown from 'markdown-to-jsx'
import styled from 'styled-components'

const MarkdownContainer = styled.div`
  code {
    @media (prefers-color-scheme: dark) {
      background-color: #374151 !important;
      color: #e5e7eb !important;
    }
    
    [data-theme="dark"] & {
      background-color: #374151 !important;
      color: #e5e7eb !important;
    }
  }
  
  pre {
    @media (prefers-color-scheme: dark) {
      background-color: #374151 !important;
      color: #e5e7eb !important;
    }
    
    [data-theme="dark"] & {
      background-color: #374151 !important;
      color: #e5e7eb !important;
    }
  }
  
  blockquote {
    @media (prefers-color-scheme: dark) {
      background-color: #1e3a8a !important;
      border-left-color: #3b82f6 !important;
      color: #e5e7eb !important;
    }
    
    [data-theme="dark"] & {
      background-color: #1e3a8a !important;
      border-left-color: #3b82f6 !important;
      color: #e5e7eb !important;
    }
  }
`

interface MarkdownRendererProps {
  content: string
  className?: string
}

export function MarkdownRenderer({ content, className }: MarkdownRendererProps) {
  return (
    <MarkdownContainer className={className}>
      <Markdown
        options={{
          overrides: {
            // Custom styling for markdown elements with better spacing
            p: {
              props: {
                style: { 
                  marginBottom: '12px',
                  lineHeight: '1.5',
                  color: 'inherit'
                }
              }
            },
            strong: {
              props: {
                style: {
                  fontWeight: 700,
                  color: 'inherit'
                }
              }
            },
            em: {
              props: {
                style: {
                  fontStyle: 'italic',
                  color: 'inherit'
                }
              }
            },
            code: {
              props: {
                style: {
                  backgroundColor: '#f3f4f6',
                  padding: '2px 6px',
                  borderRadius: '4px',
                  fontSize: '14px',
                  fontFamily: 'monospace',
                  color: '#111827'
                }
              }
            },
            pre: {
              props: {
                style: {
                  backgroundColor: '#f3f4f6',
                  padding: '12px',
                  borderRadius: '6px',
                  fontSize: '14px',
                  fontFamily: 'monospace',
                  color: '#111827',
                  overflowX: 'auto',
                  marginBottom: '12px'
                }
              }
            },
            ul: {
              props: {
                className: "list-disc list-inside mb-3 space-y-1 ml-2"
              }
            },
            ol: {
              props: {
                className: "list-decimal list-inside mb-3 space-y-1 ml-2"
              }
            },
            li: {
              props: {
                className: "leading-relaxed"
              }
            },
            blockquote: {
              props: {
                style: {
                  borderLeft: '4px solid #93c5fd',
                  paddingLeft: '16px',
                  padding: '8px',
                  fontStyle: 'italic',
                  marginBottom: '12px',
                  backgroundColor: '#eff6ff',
                  borderRadius: '4px',
                  color: 'inherit'
                }
              }
            },
            h1: {
              props: {
                style: {
                  fontSize: '20px',
                  fontWeight: 700,
                  marginBottom: '12px',
                  color: 'inherit'
                }
              }
            },
            h2: {
              props: {
                style: {
                  fontSize: '18px',
                  fontWeight: 700,
                  marginBottom: '8px',
                  color: 'inherit'
                }
              }
            },
            h3: {
              props: {
                style: {
                  fontSize: '16px',
                  fontWeight: 700,
                  marginBottom: '8px',
                  color: 'inherit'
                }
              }
            },
            h4: {
              props: {
                style: {
                  fontSize: '14px',
                  fontWeight: 700,
                  marginBottom: '8px',
                  color: 'inherit'
                }
              }
            },
            h5: {
              props: {
                style: {
                  fontSize: '14px',
                  fontWeight: 700,
                  marginBottom: '8px',
                  color: 'inherit'
                }
              }
            },
            h6: {
              props: {
                style: {
                  fontSize: '14px',
                  fontWeight: 700,
                  marginBottom: '8px',
                  color: 'inherit'
                }
              }
            },
            hr: {
              props: {
                style: {
                  margin: '16px 0',
                  borderColor: '#e5e7eb',
                  borderWidth: '1px',
                  borderStyle: 'solid'
                }
              }
            },
            a: {
              props: {
                style: {
                  color: '#2563eb',
                  textDecoration: 'underline'
                },
                target: "_blank",
                rel: "noopener noreferrer"
              }
            }
          }
        }}
      >
        {content}
      </Markdown>
    </MarkdownContainer>
  )
}

// vue2/src/components/MarkdownRenderer.vue
<template>
  <div class="markdown-content" v-html="renderedContent"></div>
</template>

<script>
import Markdown from 'markdown-to-jsx'

export default {
  name: 'MarkdownRenderer',
  props: {
    content: {
      type: String,
      required: true,
    },
  },
  computed: {
    renderedContent() {
      if (!this.content) return ''

      try {
        // Convert markdown to JSX-like HTML
        const html = Markdown(this.content, {
          wrapper: 'div',
          forceWrapper: true,
          overrides: {
            // Custom overrides for better styling
            p: {
              props: {
                style: 'margin: 0.5em 0; line-height: 1.6;',
              },
            },
            code: {
              props: {
                style:
                  'background-color: #f3f4f6; padding: 0.2em 0.4em; border-radius: 3px; font-family: monospace; font-size: 0.9em;',
              },
            },
            pre: {
              props: {
                style:
                  'background-color: #f3f4f6; padding: 1em; border-radius: 6px; overflow-x: auto; margin: 1em 0;',
              },
            },
            ul: {
              props: {
                style: 'margin: 0.5em 0; padding-left: 1.5em;',
              },
            },
            ol: {
              props: {
                style: 'margin: 0.5em 0; padding-left: 1.5em;',
              },
            },
            li: {
              props: {
                style: 'margin: 0.25em 0;',
              },
            },
            strong: {
              props: {
                style: 'font-weight: 600;',
              },
            },
            em: {
              props: {
                style: 'font-style: italic;',
              },
            },
            blockquote: {
              props: {
                style:
                  'border-left: 4px solid #e5e7eb; padding-left: 1em; margin: 1em 0; color: #6b7280;',
              },
            },
          },
        })

        return html
      } catch (error) {
        console.warn('Failed to render markdown:', error)
        return this.content
      }
    },
  },
}
</script>

<style scoped>
.markdown-content {
  word-wrap: break-word;
  overflow-wrap: break-word;
}

/* Dark mode support */
@media (prefers-color-scheme: dark) {
  .markdown-content :deep(code) {
    background-color: #374151 !important;
    color: #f9fafb !important;
  }

  .markdown-content :deep(pre) {
    background-color: #374151 !important;
    color: #f9fafb !important;
  }

  .markdown-content :deep(blockquote) {
    border-left-color: #4b5563 !important;
    color: #9ca3af !important;
  }
}
</style>
