// vue2/src/components/ProfessionalInput.vue
<template>
  <textarea
    ref="textarea"
    :value="value"
    :placeholder="placeholder"
    :disabled="disabled"
    @input="handleInput"
    @keydown="handleKeyDown"
    @focus="handleFocus"
    @blur="handleBlur"
    class="professional-input"
  />
</template>

<script>
export default {
  name: 'ProfessionalInput',
  props: {
    value: {
      type: String,
      default: '',
    },
    placeholder: {
      type: String,
      default: 'Type a message...',
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },
  methods: {
    handleInput(event) {
      this.$emit('input', event.target.value)
      this.autoResize()
    },

    handleKeyDown(event) {
      this.$emit('keydown', event)
    },

    handleFocus(event) {
      this.$emit('focus', event)
    },

    handleBlur(event) {
      this.$emit('blur', event)
    },

    autoResize() {
      this.$nextTick(() => {
        const textarea = this.$refs.textarea
        if (textarea) {
          textarea.style.height = 'auto'
          const scrollHeight = textarea.scrollHeight
          const maxHeight = 120 // max-height from CSS
          textarea.style.height = Math.min(scrollHeight, maxHeight) + 'px'
        }
      })
    },

    focus() {
      this.$nextTick(() => {
        if (this.$refs.textarea) {
          this.$refs.textarea.focus()
        }
      })
    },
  },

  watch: {
    value() {
      this.autoResize()
    },
  },

  mounted() {
    this.autoResize()
  },
}
</script>

<style scoped>
.professional-input {
  flex: 1;
  width: 100%;
  min-height: 40px;
  max-height: 120px;
  padding: 8px 12px;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  background-color: #ffffff;
  color: #1f2937;
  font-size: 14px;
  font-family: inherit;
  resize: none;
  outline: none;
  transition: all 0.2s ease;
  box-sizing: border-box;
}

.professional-input::placeholder {
  color: #6b7280;
}

.professional-input:focus {
  border-color: #3b82f6;
  box-shadow: 0 0 0 2px rgba(59, 130, 246, 0.2);
}

.professional-input:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

/* Dark mode support */
@media (prefers-color-scheme: dark) {
  .professional-input {
    background-color: #374151;
    color: #f9fafb;
    border-color: #4b5563;
  }

  .professional-input::placeholder {
    color: #9ca3af;
  }

  .professional-input:focus {
    border-color: #3b82f6;
    box-shadow: 0 0 0 2px rgba(59, 130, 246, 0.2);
  }
}
</style>

// src/components/ProfessionalInput.tsx
import { cn } from '@/utils'
import React from 'react'

interface ProfessionalInputProps {
  value: string
  onChange: (value: string) => void
  onKeyDown: (e: React.KeyboardEvent) => void
  placeholder?: string
  disabled?: boolean
  className?: string
  maxLength?: number
}

export const ProfessionalInput = React.forwardRef<HTMLTextAreaElement, ProfessionalInputProps>(({
  value,
  onChange,
  onKeyDown,
  placeholder = "Type a message...",
  disabled = false,
  className,
  maxLength = 2000
}, ref) => {
  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    onChange(e.target.value)
  }

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    // Allow normal text editing
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      onKeyDown(e)
    } else {
      onKeyDown(e)
    }
  }

  return (
    <textarea
      ref={ref}
      value={value}
      onChange={handleChange}
      onKeyDown={handleKeyDown}
      placeholder={placeholder}
      disabled={disabled}
      maxLength={maxLength}
      className={cn(
        'w-full resize-none border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 placeholder:text-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent disabled:cursor-not-allowed disabled:opacity-50 rounded-md',
        '!bg-white !text-gray-900 !border-gray-300 !w-full', // Force override any theme conflicts
        className
      )}
      rows={1}
      style={{
        minHeight: '40px',
        maxHeight: '120px',
        overflow: 'hidden',
        backgroundColor: '#ffffff',
        color: '#1f2937',
        borderColor: '#d1d5db',
        border: '1px solid #d1d5db',
        width: '100%'
      }}
      onInput={(e) => {
        const target = e.target as HTMLTextAreaElement
        target.style.height = 'auto'
        target.style.height = `${Math.min(target.scrollHeight, 120)}px`
      }}
    />
  )
})
